version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    ignore:
      - dependency-name: "ba-st-actions/pharo-ci"
    groups:
      github-actions:
        patterns:
          - "*"
