#!/usr/bin/env bash

# Prepare Launchpad topaz input script
readonly SYSTEM_USER_PASSWORD="${GS64_SYSTEM_USER_PASSWORD:-swordfish}"
readonly STONE_NAME="${GS64_STONE_SERVICE_NAME:-gs64stone}"

set -e
readonly LAUNCHPAD_TOPAZ_SCRIPT="${GEMSTONE_GLOBAL_DIR}/launchpad-start.tpz"
set +o histexpand
echo "set stone !@${GS64_STONE_HOSTNAME}!${STONE_NAME} user SystemUser pass ${SYSTEM_USER_PASSWORD}" >> "${LAUNCHPAD_TOPAZ_SCRIPT}"
set -o histexpand

pid=0

termination_handler() {
  exit_status=0
  if [ $pid -ne 0 ]; then
    echo 'SIGTERM received, shutting down the gem'
    kill "$pid"
    stopnetldi
    wait "$pid"
    exit_status=$?
  fi
  exit "$exit_status"    
}

trap 'termination_handler' SIGTERM

if ! gslist -v -n "${NETLDI_SERVICE_NAME}" > /dev/null; then
  # shellcheck disable=SC2086
  startnetldi \
    -g \
    -a "${GS_USER}" \
    -n \
    -P "${NETLDI_PORT}" \
    -l "${GEMSTONE_LOG_DIR}/${NETLDI_SERVICE_NAME}.log" \
    -D "${GEMSTONE_LOG_DIR}" \
    ${NETLDI_ARGS:-} \
    "${NETLDI_SERVICE_NAME}" >> "${GEMSTONE_LOG_DIR}/startnetldi.log"
fi

# list GemStone services
gslist -cvl >> "${GEMSTONE_LOG_DIR}/startnetldi.log"

# Translate Launchpad environment variables into start command options
EXTRA_ARGS=()
if [[ "$LAUNCHPAD__LOG_FORMAT" == "json" ]]; then
    EXTRA_ARGS+=(--enable-structured-logging)
fi
if [[ -n "$LAUNCHPAD__SETTINGS_FILE" ]]; then
    EXTRA_ARGS+=("--settings-file=$LAUNCHPAD__SETTINGS_FILE")
fi

# These options are only valid for the start command and must precede the <app>
# argument, so inject them right after the start subcommand
LAUNCHPAD_ARGS=("$@")
if [[ "${1:-}" == "start" ]]; then
    shift
    LAUNCHPAD_ARGS=(start "${EXTRA_ARGS[@]}" "$@")
fi

topaz -l -q -I "${LAUNCHPAD_TOPAZ_SCRIPT}" -S "${GEMSTONE_GLOBAL_DIR}/command-line-handler.tpz" -- launchpad "${LAUNCHPAD_ARGS[@]}" &
pid="$!"
wait "$pid"
