#!/usr/bin/env bash

# Prepare Launchpad topaz input script
readonly SYSTEM_USER_PASSWORD="${GS64_SYSTEM_USER_PASSWORD:-swordfish}"
readonly STONE_NAME="${GS64_STONE_SERVICE_NAME:-gs64stone}"

set -e
readonly LAUNCHPAD_TOPAZ_SCRIPT="${GEMSTONE_GLOBAL_DIR}/data/launchpad-start.tpz"
set +o histexpand
echo "set gemstone !@${GS64_STONE_HOSTNAME}!${STONE_NAME} user SystemUser pass ${SYSTEM_USER_PASSWORD}" >> "${LAUNCHPAD_TOPAZ_SCRIPT}"
echo "iferror exit 1" >> "${LAUNCHPAD_TOPAZ_SCRIPT}"
echo "login" >> "${LAUNCHPAD_TOPAZ_SCRIPT}"
echo "doit" >> "${LAUNCHPAD_TOPAZ_SCRIPT}"
echo "    CommandLineHandler activateWith: CommandLineArguments new" >> "${LAUNCHPAD_TOPAZ_SCRIPT}"
echo "%" >> "${LAUNCHPAD_TOPAZ_SCRIPT}"
echo "exit 0" >> "${LAUNCHPAD_TOPAZ_SCRIPT}"
set -o histexpand

pid=0

termination_handler() {
  exit_status=0
  if [ $pid -ne 0 ]; then
    echo 'SIGTERM received, shutting down the gem'
    kill "$pid"
    stopnetldi
    wait "$pid"
    exit_status=$?
  fi
  exit "$exit_status"    
}

trap 'termination_handler' SIGTERM

# shellcheck disable=SC2086
startnetldi \
  -g \
  -a "${GS_USER}" \
  -n \
  -P "${NETLDI_PORT}" \
  -l "${GEMSTONE_LOG_DIR}/${NETLDI_SERVICE_NAME}.log" \
  -D "${GEMSTONE_LOG_DIR}" \
  ${NETLDI_ARGS:-} \
  "${NETLDI_SERVICE_NAME}"

# list GemStone services
gslist -cvl

topaz -l -S "${LAUNCHPAD_TOPAZ_SCRIPT}" -- launchpad "$@" &
pid="$!"
wait "$pid"
