#!/usr/bin/env bash

pid=0

if [[ -z $LAUNCHPAD__COMMAND_SERVER_PORT ]]; then
  LAUNCHPAD__COMMAND_SERVER_PORT=22222
fi

# SIGTERM-handler
termination_handler() {
  exit_status=0
  if [ $pid -ne 0 ]; then
    echo
    echo 'SIGTERM received, shutting down the application'
    echo "SHUTDOWN" | nc localhost "$LAUNCHPAD__COMMAND_SERVER_PORT"
    wait "$pid"
    exit_status=$?
  fi
  exit "$exit_status"
}

trap 'termination_handler' SIGTERM

EXTRA_ARGS=()
if [[ "$LAUNCHPAD__LOG_FORMAT" == "json" ]]; then
    EXTRA_ARGS+=(--enable-structured-logging)
fi
if [[ -n "$LAUNCHPAD__SETTINGS_FILE" ]]; then
    EXTRA_ARGS+=("--settings-file=$LAUNCHPAD__SETTINGS_FILE")
fi

launchpad start "${EXTRA_ARGS[@]}" --enable-tcp-command-server="$LAUNCHPAD__COMMAND_SERVER_PORT" "$@" &
pid="$!"
wait "$pid"
