name: Binary Stack Serialization Tests

on: [push,pull_request,workflow_dispatch]

jobs:
   unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-11, Pharo64-10, Pharo64-9.0, Pharo64-8.0 ]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v3
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Load Image and Run Tests
        # We can't run these tests with the coverage enabled because it will modify the stack it's
        # trying to serialize making the tests fail in some situations
        run: smalltalkci -s ${{ matrix.smalltalk }} .smalltalkci/.binary-stack-serialization.ston
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 15
