name: Scheduled vulnerability scanning
on:
  schedule:
    - cron: '35 6 * * 2'
  workflow_dispatch:
jobs:
  vulnerability-scan:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - latest
          - v7
        package:
          - launchpad
          - launchpad-gs64-3.7.1
    name: Scheduled scan for vulnerabilities ${{ matrix.package }}-${{ matrix.version }}
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/${{ matrix.package }}:${{ matrix.version}}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          limit-severities-for-sarif: true
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          category: ghcr.io/${{ github.repository_owner }}/${{ matrix.package }}:${{ matrix.version}}
